import { cn } from '@/utils/class-merge'
import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { ReactNode } from 'react'
import { Providers } from './providers'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body
                className={cn(
                    nunito.className,
                    'h-screen bg-gray-800 p-5 text-gray-100',
                )}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
